services:
  - type: web
    name: fgt-ecommerce-backend
    env: node
    repo: https://gitlab.com/edgthiago-group/edgthiago-project.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    branch: dashboard
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: fgt-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: fgt-mysql
          property: port
      - key: DB_USER
        fromDatabase:
          name: fgt-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fgt-mysql
          property: password
      - key: DB_NAME
        fromDatabase:
          name: fgt-mysql
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "*"

databases:
  - name: fgt-mysql
    databaseName: loja_tenis
    user: admin
    plan: free
    region: oregon
